repos:
    - repo: https://github.com/astral-sh/uv-pre-commit
      rev: 0.5.16
      hooks:
          - id: uv-lock
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.0
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
